### PR TITLE
feat(design-system): shared token system + 8 reusable UI components

### LINKED ISSUE #1: [EPIC A] Design System & Visual Overhaul
## Overview
Establish a cohesive, production-grade design system and overhaul all existing views to match it.

## Motivation
The initial scaffolded views used bare SwiftUI defaults — no consistent spacing, colour, or typography. A shared design token layer eliminates drift and makes future changes one-line edits.

## Acceptance Criteria
- [ ] `DesignSystem.swift` — colour tokens (background layers, semantic, call-type, status, chart palette), typography scale (`appLargeTitle` → `appCaption2`), spacing enum, corner-radius enum, shadow presets, animation constants, `CardModifier`
- [ ] `Components/VisualEffectView.swift` — `NSVisualEffectView` SwiftUI wrapper for sidebar vibrancy / under-window blur
- [ ] `Components/StatCard.swift` — animated KPI card (icon + value + label + optional subtitle)
- [ ] `Components/ToastView.swift` + `ToastManager` — slide-in toast notification system, auto-dismiss after 3 s, four styles (success / error / warning / info)
- [ ] `Components/ChartCard.swift` — reusable card container for every chart (title, subtitle, optional action menu)
- [ ] `Components/EmptyStateView.swift` — generic animated empty-state (SF Symbol icon, title, body copy, optional CTA button)
- [ ] `Components/PillBadge.swift` — pill-shaped label used for call type and status columns
- [ ] `Components/DonutChartView.swift` — pure-`Path` donut chart compatible with macOS 13 (replacement for `SectorMark` which requires macOS 14)
- [ ] `ContentView.swift` rewrite — custom toolbar, sheet registration, global toast overlay
- [ ] `BackupListView.swift` rewrite — card-based sidebar with vibrancy, device icons, encrypted badge, empty state
- [ ] `BackupDetailView.swift` rewrite — tab switcher (Records | Analytics), state machine orchestration
- [ ] `PasswordEntryView.swift` rewrite — split-panel layout with gradient hero, animated lock icon, show/hide password
- [ ] `CallHistoryTableView.swift` rewrite — KPI strip, avatar initials, context menus, row hover
- [ ] `FilterBarView.swift` rewrite — chip-style active-filter dismissal, collapsible expanded row, date pickers
- [ ] `DeleteConfirmationView.swift` rewrite — risk-styled sheet with scrollable record preview
- [ ] `RestoreInstructionsView.swift` rewrite — numbered step-by-step timeline with SF Symbol icons

## Files
`DesignSystem.swift`, `Components/VisualEffectView.swift`, `Components/StatCard.swift`, `Components/ToastView.swift`, `Components/ChartCard.swift`, `Components/EmptyStateView.swift`, `Components/PillBadge.swift`, `Components/DonutChartView.swift`, all Views

## Labels
`epic`, `frontend`, `design-system`

### PR DESCRIPTION
**Pull request by sanskarpan**
## Summary
- `DesignSystem.swift` — complete design token layer: colour semantic aliases, 10-step type scale, spacing/radius/shadow enums, `CardModifier` view modifier, animation constants
- `VisualEffectView` — `NSViewRepresentable` wrapper for NSVisualEffectView (sidebar vibrancy)
- `StatCard` — animated KPI card used in the analytics dashboard header row
- `ToastView` + `ToastManager` — global slide-in notification system with 4 styles and 3 s auto-dismiss
- `ChartCard` — card container for all chart sections (title, subtitle, optional action menu)
- `EmptyStateView` — animated SF Symbol empty state with optional action button
- `PillBadge` — pill-shaped badge for call type (Phone / FaceTime Video / FaceTime Audio) and status columns
- `DonutChartView` — **macOS 13 compatible** donut chart via `Path.addArc` (avoids `SectorMark` which requires macOS 14)

## Key Design Decisions
- `SectorMark` from Swift Charts requires macOS 14.0 — replaced with a pure-`Path` implementation that works on 13.0+
- `Radius.xs = 4` added to fix compilation error in `AnalyticsDashboardView` `.cornerRadius(Radius.xs)` call
- All spacing via `Spacing.*` enum constants — no magic numbers in views

## Test plan
- [x] `ToastManager.show()` appends toast; auto-dismiss fires after 3 s
- [x] `DonutChartView` renders with 3 segments summing to non-zero total
- [x] `EmptyStateView` shows correctly in `AnalyticsDashboardView` before data loads
- [x] All components render without constraint warnings in Xcode canvas

Closes #1

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Review by sanskarpan — COMMENTED** [review]
Done
